Repository COS301-SE-2025/Gamified-Financial-Visualizer, pull requests merged in 2025-09, with the labels that each got.

#426 Game mock simulation gameplay
  frontend/src/App.jsx
  frontend/src/assets/Images/avatars/Croissant.png
  frontend/src/assets/Images/avatars/Phone.png
  frontend/src/assets/Images/avatars/Skull.png
  frontend/src/assets/Images/game/lobby-banner.png
  frontend/src/components/game/GameBoardViewer.jsx
  frontend/src/components/game/MockGameSimulation.jsx
  frontend/src/components/game/hud/GameHUD.jsx
  frontend/src/components/game/lobby/GameLobby.jsx
Labels: game

#438 Frontend mobile2
  frontend/src/pages/Accounts/Insights.jsx
Labels: frontend

#447 Pushing all the sorted hotfixes
  api-backend/db/backup_20250914_231521.sql
  api-backend/db/backup_20250914_233502.sql
  api-backend/db/backup_20250914_233858.sql
  api-backend/db/backup_20250917_194645.sql
  api-backend/db/backup_20250917_194946.sql
  api-backend/db/backup_20250917_195719.sql
  api-backend/db/reset_script.sh
  api-backend/db/schema_dump.sql
  api-backend/db/seed.sql
  api-backend/modules/ai/app/requirements.txt
  api-backend/modules/community/routes/communityRoutes.ts
  api-backend/modules/community/services/community.service.ts
  api-backend/tests/services/community.test.ts
  frontend/public/assets/Images/learn_banners/Adulting.png
  frontend/public/assets/Images/learn_banners/BigLifeChangers.png
  frontend/public/assets/Images/learn_banners/Budget.png
  frontend/public/assets/Images/learn_banners/Fomo.png
  frontend/public/assets/Images/learn_banners/Insurance.png
  frontend/public/assets/Images/learn_banners/Investment.png
  frontend/public/assets/Images/learn_banners/Money Talks.png
  frontend/public/assets/Images/learn_banners/MoneyForStudents.png
  frontend/public/assets/Images/learn_banners/MoneyTherapy.png
  frontend/public/assets/Images/learn_banners/SalaryNegotiator.png
  frontend/public/assets/Images/learn_banners/TaxMaster.png
  frontend/public/assets/Images/learn_banners/Young.png
  frontend/public/assets/Images/learn_banners/credit.png
  frontend/public/assets/Images/learn_banners/retrenchment.png
  frontend/public/assets/Images/learn_banners/sideHustle.png
  frontend/src/pages/Community/CommunityDashboard.jsx
  frontend/src/pages/Community/CommunityMemberPage.jsx
Labels: bug

#482 Completed rain theme
  frontend/src/components/city/CityViewer.jsx
  frontend/src/components/game/GameBoardViewer.jsx
Labels: AR

#505 Pushing the financial advisor
  api-backend/modules/ai/app/server.py
  api-backend/modules/ai/routes/insightsRouter.ts
  frontend/src/pages/Accounts/Insights.jsx
Labels: enhancement
