Repository COS301-SE-2025/Gamified-Financial-Visualizer, pull requests merged in 2025-07, with the labels that each got.

#239 Backend fixes to Learn and Goals modules
  api-backend/jobs/resetBudgets.ts
  api-backend/modules/goals/services/goals.service.ts
  api-backend/modules/transactions/services/transaction.service.ts
  api-backend/server.ts
  frontend/src/components/cards/GoalOverviewCards.jsx
  frontend/src/components/cards/UpcomingDeadlinesCard.jsx
  frontend/src/components/cards/categoryIcons.ts
  frontend/src/layouts/Navbar.jsx
  frontend/src/layouts/sidebars/GoalsSidebar.jsx
  frontend/src/layouts/sidebars/LearnSidebar.jsx
  frontend/src/pages/Goals/GoalCreatePage.jsx
  frontend/src/pages/Goals/GoalDetailPage.jsx
  frontend/src/pages/Goals/GoalsPage.jsx
  frontend/src/pages/Learn/LearnModulesPage.jsx
  frontend/src/pages/Profile/Settings.jsx
  frontend/src/pages/Support/HelpMain.jsx
Labels: bug

#240 Development into api-accounts
  api-backend/config/redis.ts
  api-backend/jobs/resetBudgets.ts
  api-backend/modules/goals/services/goals.service.ts
  api-backend/modules/transactions/services/transaction.service.ts
  api-backend/server.ts
  frontend/src/components/cards/GoalOverviewCards.jsx
  frontend/src/components/cards/UpcomingDeadlinesCard.jsx
  frontend/src/components/cards/categoryIcons.ts
  frontend/src/layouts/Navbar.jsx
  frontend/src/layouts/sidebars/GoalsSidebar.jsx
  frontend/src/layouts/sidebars/LearnSidebar.jsx
  frontend/src/pages/Goals/GoalCreatePage.jsx
  frontend/src/pages/Goals/GoalDetailPage.jsx
  frontend/src/pages/Goals/GoalsPage.jsx
  frontend/src/pages/Learn/LearnModulesPage.jsx
  frontend/src/pages/Profile/Settings.jsx
  frontend/src/pages/Support/HelpMain.jsx
Labels: task

#246 Pushing Latest Settings Page Integration
  api-backend/.gitignore
  api-backend/modules/auth/routes/authRoutes.ts
  api-backend/modules/auth/services/auth.service.ts
  frontend/src/layouts/Navbar.jsx
  frontend/src/layouts/sidebars/ProfileSidebar.jsx
  frontend/src/pages/Auth/Register.jsx
  frontend/src/pages/Profile/Settings.jsx
Labels: enhancement

#259 Frontend, added loaders
  frontend/src/components/loaders/LoaderUsage.txt
  frontend/src/components/loaders/PacmanLoader.jsx
  frontend/src/pages/Accounts/AccountsLayout.jsx
  frontend/tailwind.config.js
Labels: frontend

#279 Added the features to the imports
  frontend/src/components/loaders/LoaderUsage.txt
  frontend/src/components/loaders/PacmanLoader.jsx
  frontend/src/pages/Accounts/AccountsLayout.jsx
  frontend/src/pages/Accounts/Import.jsx
  frontend/tailwind.config.js
Labels: enhancement
